//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 15.02.2020 13:36:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace pineapple_shopModel
{
    public partial class Staff {

        public Staff()
        {
            this.DeliveryInfos = new List<DeliveryInfo>();
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual string Name
        {
            get;
            set;
        }

        public virtual string Passport
        {
            get;
            set;
        }

        public virtual System.DateTime DateOfBirth
        {
            get;
            set;
        }

        public virtual System.DateTime EmploymentDate
        {
            get;
            set;
        }

        public virtual int PositionId
        {
            get;
            set;
        }

        public virtual IList<DeliveryInfo> DeliveryInfos
        {
            get;
            set;
        }

        public virtual PositionsDictionary PositionsDictionary
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
